"""Declarative Report builder — the main user-facing API for detailed reports."""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd

from databloom.layout.engine import LayoutEngine
from databloom.layout.templates import (
    layout_dashboard,
    layout_report,
    layout_simple,
    layout_summary_detail,
)
from databloom.settings import settings
from databloom.theme.presets import Theme, get_theme
from databloom.utils.inspection import profile_dataframe

if TYPE_CHECKING:
    from databloom.elements.chart import ChartType


class Report:
    """Fluid builder for creating multi-sheet, multi-element Excel reports.

    Provides a chainable API that mirrors the layout engine::

        Report(title="Analysis", theme="business_blue")
            .add_sheet("Overview")
            .add_title("Sales Report")
            .add_table(summary_df)
            .add_chart(trend_df, type="line")
            .add_sheet("Details")
            .add_table(detail_df)
            .build("./output/report.xlsx")

    If ``build()`` is called without a path it returns ``bytes``, useful
    for serving reports via web APIs.

    For quick auto-detection, use the ``Report.quick()`` class method::

        Report.quick(df).build("./output/report.xlsx")

        # Extend the auto-generated report before building
        report = Report.quick(kpi_df, theme="tech_dark")
        report.add_sheet("Extra Analysis").add_paragraph("Custom notes")
        report.build("./output/report.xlsx")
    """

    def __init__(
        self,
        title: str | None = None,
        theme: str | Theme | None = None,
    ) -> None:
        """Initialize the report builder.

        Args:
            title: Report title (used as workbook-level metadata).
            theme: Theme name string or ``Theme`` instance.
        """
        self.title = title if title is not None else settings.report.default_title
        if theme is None:
            self.theme = get_theme(settings.report.default_theme_name)
        elif isinstance(theme, str):
            self.theme = get_theme(theme)
        else:
            self.theme = theme
        self._engine = LayoutEngine(self.theme)
        self._page_setup: dict | None = None

    @classmethod
    def quick(
        cls,
        *dataframes: pd.DataFrame,
        title: str | None = None,
        theme: str | Theme | None = None,
        chart_type: str = "auto",
    ) -> Report:
        """Auto-analyze DataFrames and create a ready-to-render Report instance.

        This is the declarative equivalent of ``quick_report()``.  It
        profiles each DataFrame, picks the best layout and chart types,
        and returns a ``Report`` that you can inspect, extend, or build
        immediately.

        Args:
            *dataframes: One or more pandas DataFrames to include.
            title: Report title (workbook-level).  Defaults to
                ``settings.quick_report.default_title``.
            theme: Theme name or ``Theme`` instance.  Defaults to
                ``settings.quick_report.default_theme_name``.
            chart_type: ``"auto"`` to auto-detect, or a specific type
                (``"column"``, ``"line"``, etc.).

        Returns:
            A ``Report`` instance ready to call ``.build()``.

        Example::

            # One-liner
            Report.quick(sales_df).build("./output/sales.xlsx")

            # Extend the auto-generated report
            report = Report.quick(kpi_df, detail_df, theme="tech_dark")
            report.add_sheet("Appendix").add_paragraph("Generated by databloom")
            report.build("./output/full_report.xlsx")
        """
        final_title = title if title is not None else settings.quick_report.default_title

        if theme is None:
            resolved_theme = get_theme(settings.quick_report.default_theme_name)
        elif isinstance(theme, str):
            resolved_theme = get_theme(theme)
        else:
            resolved_theme = theme

        report = cls(title=final_title, theme=resolved_theme)

        dfs = list(dataframes)

        # No DataFrames — minimal template
        if not dfs:
            report.add_sheet(settings.quick_report.default_sheet_name)
            from databloom.elements.text import ParagraphElement, TitleElement

            report._engine.place_row(TitleElement(final_title))
            report._engine.place_row(ParagraphElement(settings.quick_report.no_data_message))
            return report

        # Exactly 1 DataFrame — simple or summary_detail
        if len(dfs) == 1:
            profile = profile_dataframe(dfs[0])

            if profile.suggested_layout == "summary_detail" and len(profile.suggested_chart_types) > 0:
                summary_df = dfs[0].head(settings.quick_report.summary_head_rows)
                ct = chart_type if chart_type != "auto" else profile.suggested_chart_types[0]
                ct = ct if ct in settings.quick_report.supported_chart_types else "column"
                layout_summary_detail(
                    report._engine,
                    final_title,
                    summary_df,
                    dfs[0],
                    dfs[0],
                    chart_type=ct,  # type: ignore[arg-type]
                    chart_title=f"Overview — {profile.columns[0].name if profile.columns else 'Data'}",
                )
            else:
                layout_simple(report._engine, final_title, dfs[0])

        # 2+ DataFrames — summary_detail with first 2
        else:
            if len(dfs) > 2:
                warnings.warn(
                    f"Report.quick received {len(dfs)} DataFrames, but only the "
                    f"first 2 are used. Use the builder API for multi-DataFrame reports.",
                    stacklevel=2,
                )
            first = dfs[0]
            second = dfs[1]
            profile = profile_dataframe(first)
            ct = (
                chart_type
                if chart_type != "auto"
                else (profile.suggested_chart_types[0] if profile.suggested_chart_types else "column")
            )
            ct = ct if ct in settings.quick_report.supported_chart_types else "column"
            layout_summary_detail(
                report._engine,
                final_title,
                first.head(min(settings.quick_report.max_summary_rows, len(first))),
                first,
                second,
                chart_type=ct,  # type: ignore[arg-type]
                chart_title="Chart",
            )

        return report

    def add_sheet(self, name: str) -> Report:
        """Start a new sheet. Subsequent elements are placed on this sheet.

        Args:
            name: The Excel sheet name.

        Returns:
            ``self`` for chaining.
        """
        self._engine.add_sheet(name)
        return self

    def add_title(self, text: str) -> Report:
        """Add a main title element to the current sheet.

        Args:
            text: Title text.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.text import TitleElement

        self._engine.place_row(TitleElement(text))
        return self

    def add_subtitle(self, text: str) -> Report:
        """Add a subtitle element to the current sheet.

        Args:
            text: Subtitle text.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.text import SubtitleElement

        self._engine.place_row(SubtitleElement(text))
        return self

    def add_paragraph(self, text: str) -> Report:
        """Add a body paragraph to the current sheet.

        Args:
            text: Paragraph content.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.text import ParagraphElement

        self._engine.place_row(ParagraphElement(text))
        return self

    def add_table(
        self,
        df: pd.DataFrame,
        *,
        title: str | None = None,
        column_formats: dict[str, str] | None = None,
        freeze_panes: bool = False,
    ) -> Report:
        """Add a formatted data table to the current sheet.

        Args:
            df: Source DataFrame.
            title: Optional title row above the headers.
            column_formats: Optional custom xlsxwriter format strings per column.
            freeze_panes: Whether to freeze the header row (default False).

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.table import TableElement

        self._engine.place_row(
            TableElement(df, title=title, column_formats=column_formats, freeze_panes=freeze_panes)
        )
        return self

    def add_chart(
        self,
        df: pd.DataFrame,
        type: ChartType = "column",
        *,
        category_col: str | None = None,
        value_cols: list[str] | None = None,
        title: str = "",
        backend: str = "xlsxwriter",
    ) -> Report:
        """Add a chart to the current sheet.

        Args:
            df: Source DataFrame.
            type: Chart type (column, bar, line, pie, area, scatter).
            category_col: X-axis column name (auto-detected if omitted).
            value_cols: Y-axis column names (auto-detected if omitted).
            title: Chart title text.
            backend: ``"xlsxwriter"`` or ``"matplotlib"``.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.chart import ChartElement

        self._engine.place_row(
            ChartElement(
                df,
                chart_type=type,
                category_col=category_col,
                value_cols=value_cols,
                title=title,
                backend=backend,  # type: ignore[arg-type]
            )
        )
        return self

    def add_combo_chart(
        self,
        df: pd.DataFrame,
        *,
        category_col: str | None = None,
        bar_cols: list[str] | None = None,
        line_cols: list[str] | None = None,
        bar_title: str = "",
        line_title: str = "",
        title: str = "",
    ) -> Report:
        """Add a combination chart (columns + line, dual Y-axis) to the current sheet.

        This is the ideal chart for showing volume metrics alongside
        ratio/rate metrics — for example, monthly revenue as columns
        and profit margin as a line.

        Args:
            df: Source DataFrame.
            category_col: X-axis column name (auto-detected if omitted).
            bar_cols: Column names for the column/bar series (left Y-axis).
            line_cols: Column names for the line series (right Y-axis).
            bar_title: Label for the bar axis.
            line_title: Label for the line axis.
            title: Overall chart title.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.chart import ComboChartElement

        self._engine.place_row(
            ComboChartElement(
                df,
                category_col=category_col,
                bar_cols=bar_cols,
                line_cols=line_cols,
                bar_title=bar_title,
                line_title=line_title,
                title=title,
            )
        )
        return self

    def add_image(
        self,
        image_path: str | Path,
        *,
        scale_x: float = 1.0,
        scale_y: float = 1.0,
    ) -> Report:
        """Insert an image into the current sheet.

        Args:
            image_path: Path to a PNG/JPG file.
            scale_x: Horizontal scale factor.
            scale_y: Vertical scale factor.

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.image import ImageElement

        self._engine.place_row(ImageElement(image_path, scale_x=scale_x, scale_y=scale_y))
        return self

    def add_spacer(self, *, rows: int = 1, height: int = 12) -> Report:
        """Add a vertical gap (empty space) between elements.

        Args:
            rows: How many rows the spacer occupies.
            height: Row height in Excel points (default 12).

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.text import SpacerElement

        self._engine.place_row(SpacerElement(rows=rows, height=height))
        return self

    def add_sparkline(
        self,
        data: pd.DataFrame,
        *,
        destination_col: int = 0,
        sparkline_type: str = "line",
        low_point: bool = False,
        high_point: bool = False,
        first_point: bool = False,
        last_point: bool = False,
        negative_points: bool = False,
        markers: bool = False,
        line_weight: float = 1.0,
    ) -> Report:
        """Add in-cell sparkline mini charts from a numeric DataFrame.

        Each row in *data* becomes one sparkline, placed in the column
        indicated by *destination_col*.  Sparklines are Excel-native and
        render as tiny trend charts inside a single cell.

        .. versionadded:: 0.4.0

        Args:
            data: DataFrame containing **only numeric columns**.
            destination_col: Zero-based column index for sparkline placement.
            sparkline_type: One of ``"line"`` (default), ``"column"``, ``"win_loss"``.
            low_point: Highlight the lowest value point.
            high_point: Highlight the highest value point.
            first_point: Highlight the first data point.
            last_point: Highlight the last data point.
            negative_points: Highlight negative values.
            markers: Show data markers (line type only).
            line_weight: Line weight in points (line type only).

        Returns:
            ``self`` for chaining.
        """
        from databloom.elements.sparkline import SparklineElement

        self._engine.place_row(
            SparklineElement(
                data,
                destination_col=destination_col,
                sparkline_type=sparkline_type,
                low_point=low_point,
                high_point=high_point,
                first_point=first_point,
                last_point=last_point,
                negative_points=negative_points,
                markers=markers,
                line_weight=line_weight,
            )
        )
        return self

    def add_formula_table(
        self,
        df: pd.DataFrame,
        *,
        title: str | None = None,
        column_formats: dict[str, str] | None = None,
        freeze_panes: bool = False,
        formulas: dict[str, str] | None = None,
        formula_label: str = "Total",
        bold_formulas: bool = True,
    ) -> Report:
        """Add a styled data table with a formula summary row at the bottom.

        This is identical to ``add_table()`` but appends a footer row
        containing Excel formulas (``SUM``, ``AVERAGE``, ``MAX``, ``MIN``,
        or custom). The formula row is rendered using xlsxwriter's
        ``write_formula()`` so the computation happens live in Excel.

        Args:
            df: Source DataFrame.
            title: Optional title row above the headers.
            column_formats: Optional custom xlsxwriter format strings per column.
            freeze_panes: Whether to freeze the header row (default False).
            formulas: Dict mapping column names to formula types. Supported
                values: ``"SUM"``, ``"AVERAGE"``, ``"MAX"``, ``"MIN"``, or
                any custom Excel formula string (e.g. ``"=SUMIF(E2:E20,\">0\")"``).
                Columns not listed in this dict will have an empty formula cell.
            formula_label: Label text for the first column of the formula row.
                Defaults to ``"Total"``.
            bold_formulas: Whether the formula row uses bold font. Default True.

        Returns:
            ``self`` for chaining.

        Example::

            report.add_formula_table(
                sales_df,
                title="Monthly Sales",
                formulas={"Revenue": "SUM", "Cost": "SUM", "Margin": "AVERAGE"},
                formula_label="Summary",
            )
        """
        from databloom.elements.table import TableElement
        from databloom.elements.table import _FormulaFooterElement as _FFE

        # Place the main table first
        self._engine.place_row(
            TableElement(
                df,
                title=title,
                column_formats=column_formats,
                freeze_panes=freeze_panes,
            )
        )

        # Then place the formula footer element
        self._engine.place_row(
            _FFE(
                df=df,
                formulas=formulas or {},
                formula_label=formula_label,
                bold_formulas=bold_formulas,
            )
        )
        return self

    def set_page_setup(
        self,
        *,
        orientation: str | None = None,
        paper: int | None = None,
        margin_left: float | None = None,
        margin_right: float | None = None,
        margin_top: float | None = None,
        margin_bottom: float | None = None,
        fit_to_width: int | None = None,
        fit_to_height: int | None = None,
        print_title_rows: int | None = None,
    ) -> Report:
        """Configure page setup for printing/PDF export.

        Applied to all sheets when ``build()`` is called.

        Args:
            orientation: ``"landscape"`` or ``"portrait"``.
            paper: xlsxwriter paper type index (9 = A4, 1 = Letter, 13 = B5).
            margin_left/margin_right/margin_top/margin_bottom: Margins in inches.
            fit_to_width: Fit output to this many pages wide (0 = no limit).
            fit_to_height: Fit output to this many pages tall (0 = no limit).
            print_title_rows: Number of header rows to repeat on each printed page.

        Returns:
            ``self`` for chaining.
        """
        self._page_setup = {
            "orientation": orientation if orientation is not None else settings.report.page_orientation,
            "paper": paper if paper is not None else settings.report.page_paper,
            "margin_left": margin_left if margin_left is not None else settings.report.page_margin_left,
            "margin_right": margin_right if margin_right is not None else settings.report.page_margin_right,
            "margin_top": margin_top if margin_top is not None else settings.report.page_margin_top,
            "margin_bottom": margin_bottom if margin_bottom is not None else settings.report.page_margin_bottom,
            "fit_to_width": fit_to_width if fit_to_width is not None else settings.report.page_fit_to_width,
            "fit_to_height": fit_to_height if fit_to_height is not None else settings.report.page_fit_to_height,
            "print_title_rows": print_title_rows if print_title_rows is not None else settings.report.page_print_title_rows,
        }
        return self

    def apply_template(
        self,
        template_name: str,
        **kwargs: object,
    ) -> Report:
        """Apply a named layout template to the current state.

        Note: This clears existing manual placements on the current sheet.

        Args:
            template_name: One of ``"simple"``, ``"summary_detail"``,
                ``"dashboard"``, ``"report"``.
            **kwargs: Template-specific arguments.

        Returns:
            ``self`` for chaining.
        """
        templates: dict[str, object] = {
            "simple": layout_simple,
            "summary_detail": layout_summary_detail,
            "dashboard": layout_dashboard,
            "report": layout_report,
        }
        template_fn = templates.get(template_name)
        if template_fn is None:
            available = ", ".join(templates)
            raise ValueError(f"Template {template_name!r} not found. Available: {available}")

        # The template functions expect a LayoutEngine as first arg
        template_fn(self._engine, **kwargs)  # type: ignore[operator]
        return self

    def build(self, output: str | Path | None = None) -> bytes | None:
        """Render the report and write or return it.

        Args:
            output: File path to write the ``.xlsx``. If ``None``, returns
                the file content as ``bytes``.

        Returns:
            ``bytes`` if ``output`` is ``None``, otherwise ``None`` (file
            written to disk).
        """
        from databloom.core.workbook import WorkbookManager

        wm = WorkbookManager(output)
        try:
            self._engine.build(wm)
            if self._page_setup:
                self._apply_page_setup(wm)
        finally:
            result = wm.close()
        return result

    def _apply_page_setup(self, wm: object) -> None:
        """Apply page setup to all sheets in the workbook."""
        ps = self._page_setup
        if ps is None:
            return
        for sheet_name in wm._sheets:  # type: ignore[union-attr]
            ws = wm._sheets[sheet_name]  # type: ignore[union-attr]
            if ps.get("orientation") == "landscape":
                ws.set_landscape()
            else:
                ws.set_portrait()
            ws.set_paper(ps.get("paper", settings.report.page_paper))
            ws.set_margins(
                left=ps.get("margin_left", settings.report.page_margin_left),
                right=ps.get("margin_right", settings.report.page_margin_right),
                top=ps.get("margin_top", settings.report.page_margin_top),
                bottom=ps.get("margin_bottom", settings.report.page_margin_bottom),
            )
            fit_w = ps.get("fit_to_width", settings.report.page_fit_to_width)
            fit_h = ps.get("fit_to_height", settings.report.page_fit_to_height)
            if fit_w or fit_h:
                ws.fit_to_pages(fit_w, fit_h)
            title_rows = ps.get("print_title_rows", settings.report.page_print_title_rows)
            if title_rows > 0:
                ws.repeat_rows(0, title_rows - 1)
